// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context) (int64, error)
	FindUserByID(ctx context.Context) (*FindUserByIDRow, error)
	FindUserWithCheckingPassword(ctx context.Context) (*FindUserWithCheckingPasswordRow, error)
}

var _ Querier = (*Queries)(nil)
