// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO ` + "`" + `users` + "`" + ` (` + "`" + `first_name` + "`" + `, ` + "`" + `last_name` + "`" + `, ` + "`" + `password` + "`" + `, ` + "`" + `gender` + "`" + `, ` + "`" + `birthday` + "`" + `)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	FirstName string      `db:"first_name" json:"first_name"`
	LastName  string      `db:"last_name" json:"last_name"`
	Password  string      `db:"password" json:"password"`
	Gender    UsersGender `db:"gender" json:"gender"`
	Birthday  time.Time   `db:"birthday" json:"birthday"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Password,
		arg.Gender,
		arg.Birthday,
	)
}

const findUserByID = `-- name: FindUserByID :one
SELECT ` + "`" + `first_name` + "`" + `, ` + "`" + `last_name` + "`" + `, ` + "`" + `gender` + "`" + `, ` + "`" + `birthday` + "`" + `, ` + "`" + `created_at` + "`" + `
FROM ` + "`" + `users` + "`" + ` WHERE ` + "`" + `id` + "`" + ` = ? LIMIT 1
`

type FindUserByIDRow struct {
	FirstName string      `db:"first_name" json:"first_name"`
	LastName  string      `db:"last_name" json:"last_name"`
	Gender    UsersGender `db:"gender" json:"gender"`
	Birthday  time.Time   `db:"birthday" json:"birthday"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) FindUserByID(ctx context.Context, id int32) (*FindUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Birthday,
		&i.CreatedAt,
	)
	return &i, err
}

const findUserWithCheckingPassword = `-- name: FindUserWithCheckingPassword :one
SELECT ` + "`" + `first_name` + "`" + `, ` + "`" + `last_name` + "`" + `, ` + "`" + `gender` + "`" + `, ` + "`" + `birthday` + "`" + `, ` + "`" + `created_at` + "`" + `
FROM ` + "`" + `users` + "`" + ` WHERE ` + "`" + `id` + "`" + ` = ? AND ` + "`" + `password` + "`" + ` = ? LIMIT 1
`

type FindUserWithCheckingPasswordParams struct {
	ID       int32  `db:"id" json:"id"`
	Password string `db:"password" json:"password"`
}

type FindUserWithCheckingPasswordRow struct {
	FirstName string      `db:"first_name" json:"first_name"`
	LastName  string      `db:"last_name" json:"last_name"`
	Gender    UsersGender `db:"gender" json:"gender"`
	Birthday  time.Time   `db:"birthday" json:"birthday"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) FindUserWithCheckingPassword(ctx context.Context, arg FindUserWithCheckingPasswordParams) (*FindUserWithCheckingPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, findUserWithCheckingPassword, arg.ID, arg.Password)
	var i FindUserWithCheckingPasswordRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Birthday,
		&i.CreatedAt,
	)
	return &i, err
}
