// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	FindUserByID(ctx context.Context, id int32) (*FindUserByIDRow, error)
	InsertUserCity(ctx context.Context, arg InsertUserCityParams) error
	InsertUserHobby(ctx context.Context, arg InsertUserHobbyParams) error
	UpsertCity(ctx context.Context, name string) (sql.Result, error)
	UpsertHobby(ctx context.Context, name string) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
